import os
import re

files = {
    '3-resources/wiki/concepts/CONCEPT_THINK_5_Whys.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Điểm môn Toán giảm sút\n*Tình huống: Điểm trung bình môn Toán của khối 10 giảm 15% so với năm ngoái.*\n- **Đầu vào:** Phân tích 5 Whys.\n- **Cách giải quyết:** Tại sao điểm giảm? Vì học sinh làm sai nhiều câu hình học. Tại sao? Vì không hiểu bài giảng. Tại sao? Vì bài giảng trực tuyến bị lag. Tại sao? Vì Wi-Fi trường yếu khu vực tầng 3. Tại sao? Vì router tầng 3 bị hỏng chưa thay.\n\n### Ví dụ 2: Sinh viên bỏ học (Dropout)\n*Tình huống: Tỷ lệ sinh viên năm nhất nghỉ học sau học kỳ 1 tăng đột biến.*\n- **Đầu vào:** Dữ liệu khảo sát và log hệ thống LMS.\n- **Cách giải quyết:** Tại sao nghỉ? Vì nợ môn quá nhiều. Tại sao nợ môn? Vì không theo kịp tiến độ. Tại sao không theo kịp? Vì thiếu kỹ năng tự học đại học. Tại sao thiếu? Vì tuần định hướng (Orientation) không dạy kỹ năng này. Giải pháp: Thêm module Kỹ năng tự học vào tuần định hướng năm sau.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Action_Plan_Execution.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Kế hoạch nâng cấp LMS\n*Tình huống: Kế hoạch chuyển đổi sang hệ thống Moodle mới trong hè.*\n- **Đầu vào:** Bản kế hoạch hành động với các mốc thời gian.\n- **Cách giải quyết:** Tuần 1-2: IT cài đặt server. Tuần 3-4: Migrate dữ liệu sinh viên. Tuần 5: Đào tạo giảng viên sử dụng. Phân công rõ ràng người chịu trách nhiệm từng đầu việc (RACI matrix) để đảm bảo hệ thống sẵn sàng trước khai giảng.\n\n### Ví dụ 2: Kế hoạch phụ đạo học sinh yếu\n*Tình huống: Cải thiện điểm cho 50 học sinh dưới trung bình môn Tiếng Anh.*\n- **Đầu vào:** Danh sách học sinh và điểm yếu từng kỹ năng.\n- **Cách giải quyết:** Hành động: Mở lớp phụ đạo. Người phụ trách: Cô Lan. Thời gian: Chiều thứ 3, 5 hàng tuần. Ngân sách: Miễn phí. KPI: 80% học sinh qua môn ở bài thi tháng sau.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Clustering_KMeans.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Phân cụm học sinh theo hành vi học tập\n*Tình huống: Dùng K-Means (K=3) để phân nhóm 1000 sinh viên trên hệ thống E-learning.*\n- **Đầu vào:** Dữ liệu về số giờ xem video và số lượng bài tập hoàn thành.\n- **Cách giải quyết:** AI chia thành 3 cụm: (1) Nhóm chăm chỉ (xem nhiều, làm nhiều) - cần giao thêm bài tập nâng cao; (2) Nhóm đối phó (xem ít, làm bài vội vàng) - cần giám sát chặt; (3) Nhóm gặp khó khăn (xem nhiều, điểm thấp) - cần giáo viên kèm cặp trực tiếp.\n\n### Ví dụ 2: Tối ưu hóa điểm đón xe buýt trường\n*Tình huống: Trường học muốn đặt 5 trạm xe buýt mới phục vụ sinh viên ngoại trú.*\n- **Đầu vào:** Tọa độ địa lý (GPS) nhà của 500 sinh viên ngoại trú.\n- **Cách giải quyết:** Thuật toán K-Means (K=5) sẽ tự động tính toán và gom cụm vị trí nhà sinh viên, từ đó gợi ý tọa độ trung tâm (Centroid) của 5 cụm làm vị trí lý tưởng nhất để đặt trạm xe buýt, giảm thiểu quãng đường đi bộ.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_CoNVO_Framework.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: CoNVO cho Hệ thống Cảnh báo sớm (Early Warning System)\n*Tình huống: Xây dựng model dự đoán sinh viên rớt môn.*\n- **Context:** Tỷ lệ rớt môn đại cương quá cao (30%).\n- **Need:** Cần biết sinh viên nào có nguy cơ rớt trước kỳ thi giữa kỳ 2 tuần.\n- **Vision:** Bảng dashboard hàng ngày hiển thị danh sách sinh viên rủi ro kèm lý do.\n- **Outcome:** Cố vấn học tập dùng danh sách này gọi điện can thiệp sớm, giảm tỷ lệ rớt xuống 15%.\n\n### Ví dụ 2: CoNVO cho Tối ưu thư viện\n*Tình huống: Quyết định mua thêm sách giáo khoa mới.*\n- **Context:** Thư viện luôn quá tải mùa thi, sinh viên phàn nàn thiếu sách.\n- **Need:** Cần biết tựa sách nào có nhu cầu mượn cao nhất nhưng thiếu bản cứng.\n- **Vision:** Một báo cáo Excel đơn giản liệt kê Top 50 sách thiếu hụt kèm dự toán chi phí.\n- **Outcome:** Giám đốc thư viện duyệt chi ngân sách mua thêm 500 cuốn sách phù hợp nhất ngay trong tháng.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Data_Argumentation.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Lập luận xin cấp ngân sách phòng Lab\n*Tình huống: Trưởng khoa CNTT xin nhà trường đầu tư thêm 20 máy tính cấu hình cao.*\n- **Đầu vào:** Lập luận dựa trên dữ liệu (Data Argumentation).\n- **Cách giải quyết:** Claim: "Chúng ta cần 20 máy mới". Evidence: "Dữ liệu log phòng máy cho thấy máy hiện tại mất 45 phút để chạy xong mô hình AI, làm sinh viên không kịp làm bài thực hành trong 1 ca học". Warrant: "Việc học viên không làm xong bài trực tiếp ảnh hưởng đến chuẩn đầu ra".\n\n### Ví dụ 2: Lập luận thay đổi phương pháp thi\n*Tình huống: Đề xuất chuyển từ thi tự luận sang làm Project môn Lịch sử.*\n- **Đầu vào:** Dữ liệu khảo sát sinh viên và điểm số đối chứng.\n- **Cách giải quyết:** Claim: "Project hiệu quả hơn tự luận". Evidence: "Khảo sát cho thấy 85% học sinh nhớ kiến thức lâu hơn sau 3 tháng làm project so với học vẹt đi thi". Rebuttal: "Dù project tốn thời gian chấm hơn, ta có thể dùng Rubric chuẩn hóa để giảm tải cho giáo viên".\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Data_Ethics_Scoping.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Quyền riêng tư của sinh viên\n*Tình huống: Lắp đặt camera AI phân tích cảm xúc (vui, buồn, chán) trong lớp học.*\n- **Đầu vào:** Đánh giá đạo đức dữ liệu (Data Ethics).\n- **Cách giải quyết:** Dự án bị hủy vì vi phạm quyền riêng tư nghiêm trọng. Thu thập dữ liệu cảm xúc liên tục mà không có sự đồng ý (Informed Consent) của phụ huynh và học sinh là phi đạo đức, dù mục đích là "cải thiện chất lượng giảng dạy".\n\n### Ví dụ 2: Thuật toán xếp lớp thiên vị\n*Tình huống: Trường dùng AI để phân luồng học sinh vào lớp chọn.*\n- **Đầu vào:** Mô hình AI phân loại dựa trên điểm số và dữ liệu lịch sử.\n- **Cách giải quyết:** Bước Scoping phát hiện AI ưu tiên nam sinh viên vào lớp chuyên Toán hơn nữ do dữ liệu lịch sử bị lệch. Đội ngũ Data Analyst phải loại bỏ biến "Giới tính" khỏi mô hình để đảm bảo công bằng (Fairness).\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Data_Evidence_Types.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Phân tích chất lượng bữa ăn bán trú\n*Tình huống: Phụ huynh phản ánh chất lượng thức ăn căng-tin trường đi xuống.*\n- **Đầu vào:** Thu thập đa dạng loại chứng cứ dữ liệu.\n- **Cách giải quyết:** Dữ liệu định lượng (Quantitative): Số lượng khay thức ăn bị đổ đi mỗi ngày tăng 20%. Dữ liệu định tính (Qualitative): Phỏng vấn ngẫu nhiên học sinh cho biết "canh quá mặn". Kết hợp hai loại chứng cứ này đưa ra kết luận vững chắc yêu cầu nhà bếp đổi thực đơn.\n\n### Ví dụ 2: Đánh giá phần mềm tiếng Anh mới\n*Tình huống: Quyết định có nên mua bản quyền phần mềm Pronunciation AI cho toàn trường hay không.*\n- **Đầu vào:** Dữ liệu thử nghiệm trên 1 lớp.\n- **Cách giải quyết:** Chứng cứ sơ cấp (Primary): Điểm thi nói của lớp dùng thử tăng trung bình 1.5 điểm. Chứng cứ thứ cấp (Secondary): Báo cáo nghiên cứu độc lập của đại học Harvard về phần mềm này cũng cho thấy hiệu quả tương tự. Quyết định: Xuống tiền mua bản quyền.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Data_Mining_Process_CRISP.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: CRISP-DM dự đoán kết quả tuyển sinh\n*Tình huống: Đại học muốn tăng tỷ lệ sinh viên chấp nhận thư mời nhập học (Yield Rate).*\n- **Đầu vào:** Áp dụng CRISP-DM.\n- **Cách giải quyết:** (1) Business Understanding: Tối ưu chi phí marketing. (2) Data Understanding: Lịch sử nộp hồ sơ, khoảng cách địa lý, điểm SAT. (3) Data Prep: Làm sạch dữ liệu, xử lý missing value. (4) Modeling: Xây dựng mô hình Random Forest. (5) Evaluation: Mô hình dự báo chính xác 85%. (6) Deployment: Tích hợp vào phần mềm tuyển sinh để tự động cấp học bổng cho ứng viên có nguy cơ từ chối cao.\n\n### Ví dụ 2: Phân tích nguyên nhân rớt môn hàng loạt\n*Tình huống: Môn Giải tích 1 có tỷ lệ rớt lên tới 40%.*\n- **Đầu vào:** Áp dụng CRISP-DM.\n- **Cách giải quyết:** Quá trình phân tích ở bước (3) Data Prep phát hiện dữ liệu điểm thành phần bị lỗi hệ thống ghi nhận. Quay lại bước (2) Data Understanding để hiểu rõ định dạng lưu trữ điểm của LMS, sau đó làm sạch lại. Đây là ví dụ cho tính chất "vòng lặp ngược" (Iterative) của CRISP-DM.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Data_Mining_Tasks.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Phân loại (Classification) học sinh yếu\n*Tình huống: Trường học muốn phân loại học sinh khối 12 thành 2 nhóm: "Đỗ tốt nghiệp" và "Nguy cơ trượt".*\n- **Đầu vào:** Điểm phẩy lớp 10, 11 và điểm chuyên cần.\n- **Cách giải quyết:** Dùng thuật toán Classification (Supervised Learning) để gán nhãn cho từng học sinh. Nếu kết quả là "Nguy cơ trượt", hệ thống tự động đưa vào lớp phụ đạo buổi tối.\n\n### Ví dụ 2: Phân tích luật kết hợp (Association Rules) thư viện\n*Tình huống: Khám phá thói quen đọc sách của sinh viên.*\n- **Đầu vào:** Lịch sử mượn sách thư viện trong 5 năm.\n- **Cách giải quyết:** Khai phá dữ liệu tìm ra quy luật (Market Basket Analysis): "Nếu sinh viên mượn sách Lập trình C++, 80% khả năng họ sẽ mượn thêm sách Cấu trúc dữ liệu và giải thuật". Giải pháp: Xếp 2 kệ sách này cạnh nhau trong thư viện.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Decision_Trees_Induction.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Cây quyết định xét duyệt học bổng\n*Tình huống: Xây dựng hệ thống tự động lọc hồ sơ xin học bổng.*\n- **Đầu vào:** Dữ liệu học sinh (GPA, Hoạt động ngoại khóa, Thu nhập gia đình).\n- **Cách giải quyết:** Cây quyết định (Decision Tree) sẽ tạo luật rẽ nhánh: (Nút 1) GPA > 3.5? -> Có -> (Nút 2) Thu nhập < $20k/năm? -> Có -> (Nút lá) Duyệt học bổng toàn phần. Rất dễ giải thích (Explainable AI) cho phụ huynh hiểu tại sao con họ trượt hay đỗ.\n\n### Ví dụ 2: Cây quyết định xử lý kỷ luật\n*Tình huống: Xây dựng cẩm nang xử lý vi phạm nội quy trường học.*\n- **Đầu vào:** Loại vi phạm, số lần tái phạm.\n- **Cách giải quyết:** (Nút 1) Có phải bạo lực học đường? -> Nếu Không -> (Nút 2) Đi học muộn quá 3 lần? -> Nếu Có -> (Nút lá) Mời phụ huynh. Cây quyết định giúp Giám thị xử lý công bằng, nhất quán thay vì cảm tính.\n\n'
    )
}

for path, replacement in files.items():
    if os.path.exists(path):
        with open(path, 'r', encoding='utf8') as f:
            content = f.read()
        
        if 'Rule 17: Double Examples' not in content:
            parts = content.rsplit('---\n', 1)
            if len(parts) == 2:
                new_content = parts[0] + replacement + '---\n' + parts[1]
                with open(path, 'w', encoding='utf8') as f:
                    f.write(new_content)
                print(f'Patched {path}')
            else:
                print(f'Could not split {path}')
        else:
            print(f'Already patched {path}')
