import os
import re

files = {
    '3-resources/wiki/concepts/CONCEPT_THINK_Ensemble_Methods.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Random Forest trong dự báo tuyển sinh\n*Tình huống: Dự báo xác suất một học sinh cấp 3 sẽ nhập học trường Đại học A.*\n- **Đầu vào:** Điểm số, khoảng cách địa lý, lịch sử web.\n- **Cách giải quyết:** Thay vì dùng 1 cây quyết định (Decision Tree) dễ bị sai số, hệ thống dùng Random Forest tạo ra 100 cây quyết định khác nhau. Mỗi cây dự đoán 1 kết quả. Kết quả cuối cùng được lấy theo đa số (Majority Vote), giúp tăng độ chính xác từ 70% lên 92%.\n\n### Ví dụ 2: Hội đồng xét duyệt kỷ luật (Học thuật)\n*Tình huống: Đánh giá học sinh vi phạm quy chế thi.*\n- **Đầu vào:** Bằng chứng gian lận.\n- **Cách giải quyết:** Về mặt khái niệm, Ensemble Methods giống như việc thành lập một Hội đồng kỷ luật gồm 5 thầy cô (mỗi người có một góc nhìn/chuyên môn khác nhau). Quyết định đuổi học chỉ được thông qua nếu đa số thành viên đồng ý, tránh sai lầm nếu chỉ 1 người quyết (Single Model).\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Entropy_Information_Gain.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Entropy trong phân loại mức độ hiểu bài\n*Tình huống: Một lớp học có 40 học sinh, sau bài kiểm tra, 20 em được 10 điểm và 20 em được 0 điểm.*\n- **Đầu vào:** Phân bố điểm số.\n- **Cách giải quyết:** Sự hỗn loạn (Entropy) lúc này là cao nhất (1.0) vì bạn không thể đoán chắc học sinh tiếp theo được điểm cao hay thấp. Giáo viên nhận ra cần chia lớp thành 2 nhóm trình độ để dạy thay vì dạy chung 1 giáo án.\n\n### Ví dụ 2: Information Gain chọn câu hỏi bài test\n*Tình huống: Thiết kế bài thi trắc nghiệm tiếng Anh.*\n- **Đầu vào:** Ngân hàng 100 câu hỏi.\n- **Cách giải quyết:** Dùng Information Gain để chọn câu hỏi đầu tiên. Câu số 5 có Information Gain lớn nhất vì nó phân loại rõ ràng 50% học sinh giỏi làm được và 50% học sinh yếu làm sai. Câu hỏi này giúp "giảm bớt sự không chắc chắn" (Information Gain) về trình độ học sinh tốt nhất.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Expected_Value_Framework.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Expected Value mở ngành học mới\n*Tình huống: Trường đại học cân nhắc mở chuyên ngành Trí tuệ Nhân tạo.*\n- **Đầu vào:** Xác suất tuyển sinh thành công và doanh thu dự kiến.\n- **Cách giải quyết:** (70% thành công * Doanh thu 10 tỷ) + (30% thất bại * Lỗ 3 tỷ setup phòng Lab) = 7 tỷ - 0.9 tỷ = 6.1 tỷ. Giá trị kỳ vọng (Expected Value) dương lớn, trường quyết định mở ngành.\n\n### Ví dụ 2: Tính toán gửi thư cấp học bổng\n*Tình huống: Gửi thư mời cấp học bổng tốn $50/thư (chi phí in ấn, xử lý hồ sơ), nếu sinh viên đồng ý nhập học trường lãi $5000.*\n- **Đầu vào:** AI dự báo xác suất sinh viên A nhập học là 2%.\n- **Cách giải quyết:** Expected Value = (0.02 * 5000) - (0.98 * 50) = 100 - 49 = $51. Vì EV dương, trường sẽ gửi thư cho sinh viên này dù xác suất trúng rất thấp.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Hypothesis_Pyramid.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Kim tự tháp về chất lượng bữa ăn bán trú\n*Tình huống: Học sinh phàn nàn thức ăn căng-tin dở.*\n- **Đầu vào:** Xây dựng Hypothesis Pyramid.\n- **Cách giải quyết:** Khẳng định chính (Đỉnh tháp): "Cần thay đổi nhà cung cấp thực phẩm trường học". Luận điểm phụ (Tầng 2): (1) Chất lượng nguyên liệu đi xuống; (2) Thực đơn lặp lại gây chán; (3) Giá thành không tương xứng. Bằng chứng (Tầng 3): (1.1) Hình ảnh rau héo; (2.1) Thực đơn 3 tuần không đổi; (3.1) Bảng so sánh giá căng-tin bên ngoài.\n\n### Ví dụ 2: Khẳng định đầu tư hệ thống LMS\n*Tình huống: Thuyết phục Ban giám hiệu mua hệ thống Canvas.*\n- **Đầu vào:** Xây dựng Hypothesis Pyramid theo tư duy Top-down.\n- **Cách giải quyết:** Governing Thought: "Canvas LMS sẽ tăng 20% hiệu suất quản lý đào tạo". Đi xuống dưới là 3 trụ cột: (1) Tính năng chấm thi tự động; (2) Báo cáo phân tích học tập theo thời gian thực; (3) Tính ổn định cao mùa thi. Mỗi trụ cột được chống đỡ bằng số liệu demo thực tế.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Hypothesis_Testing.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Kiểm định phương pháp giảng dạy mới\n*Tình huống: Trường áp dụng phương pháp "Lớp học đảo ngược" (Flipped Classroom) cho lớp 10A, lớp 10B vẫn học truyền thống.*\n- **Đầu vào:** Điểm kiểm tra cuối kỳ của 2 lớp.\n- **Cách giải quyết:** Đặt giả thuyết H0 (Không có sự khác biệt về điểm giữa 2 lớp). H1 (Lớp 10A điểm cao hơn). Dùng T-Test, kết quả p-value = 0.02 (nhỏ hơn 0.05). Bác bỏ H0, khẳng định Flipped Classroom thực sự hiệu quả, không phải do ngẫu nhiên.\n\n### Ví dụ 2: Kiểm định A/B cho giao diện khóa học online\n*Tình huống: Nền tảng EdTech thay đổi màu nút "Đăng ký học" từ Xanh dương sang Đỏ.*\n- **Đầu vào:** Số lượng click (Conversion Rate) của 2 nhóm user.\n- **Cách giải quyết:** H0: Đổi màu không làm tăng lượt đăng ký. Chạy A/B Testing trong 1 tuần. Nhóm màu Đỏ tăng 15% tỷ lệ click với p-value = 0.01. Khẳng định sự khác biệt có ý nghĩa thống kê (Statistically Significant), áp dụng màu Đỏ cho toàn hệ thống.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Logic_Tree.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Logic Tree giải quyết tỷ lệ tuyển sinh giảm\n*Tình huống: Số lượng hồ sơ nộp vào trường giảm 20% năm nay.*\n- **Đầu vào:** Phân tích nguyên nhân bằng "Why Tree".\n- **Cách giải quyết:** Chia nhánh theo MECE: (1) Nguyên nhân bên ngoài (Kinh tế khó khăn, Đối thủ mở ngành mới) / (2) Nguyên nhân bên trong (Chương trình học cũ kỹ, Marketing kém). Tiếp tục chẻ nhánh Marketing kém -> Không chạy Ads Facebook, Nội dung nhàm chán.\n\n### Ví dụ 2: Cây giải pháp "How Tree" cải thiện thư viện\n*Tình huống: Thư viện muốn tăng không gian ngồi đọc sách cho sinh viên mà không có tiền mở rộng diện tích.*\n- **Đầu vào:** Phân tích giải pháp bằng "How Tree".\n- **Cách giải quyết:** (1) Tăng công năng không gian hiện tại (Đổi bàn tròn thành bàn chữ nhật ghép sát, Bỏ bớt giá sách giấy chuyển sang sách điện tử); (2) Phân luồng thời gian (Khuyến khích mượn về nhà, Đặt lịch đặt chỗ trước).\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Logistic_Regression_Classifier.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Dự báo sinh viên gia hạn khóa học\n*Tình huống: Trung tâm ngoại ngữ muốn biết học viên có đóng tiền học khóa tiếp theo hay không.*\n- **Đầu vào:** Số buổi đi học, Điểm bài test cuối khóa, Tương tác với giáo viên.\n- **Cách giải quyết:** Dùng Logistic Regression để tính xác suất (từ 0 đến 1). Nếu xác suất > 0.5, dự báo là "Có gia hạn". Nếu một học viên có xác suất 0.45 (Cận ngưỡng), sale sẽ gọi điện tặng voucher 10% để đẩy xác suất lên qua 0.5.\n\n### Ví dụ 2: Phân loại email khiếu nại của phụ huynh\n*Tình huống: Hộp thư của trường nhận hàng trăm email mỗi ngày.*\n- **Đầu vào:** Nội dung văn bản email.\n- **Cách giải quyết:** AI dùng Logistic Regression (phân loại nhị phân) dự đoán: Email này là "Thắc mắc thông thường" (0) hay "Khiếu nại/Phàn nàn" (1) dựa trên các từ khóa bực bội. Email loại 1 sẽ tự động dán nhãn Đỏ (Urgent) chuyển thẳng lên Ban giám hiệu.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Naive_Bayes_Logic.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Bộ lọc Spam email trường học\n*Tình huống: Hệ thống mail nội bộ sinh viên bị tấn công bởi mail lừa đảo học bổng.*\n- **Đầu vào:** Từ khóa trong email ("Miễn phí", "Click ngay", "Học bổng 100%").\n- **Cách giải quyết:** Thuật toán Naive Bayes tính xác suất: Vì từ "Click ngay" xuất hiện nhiều trong các mail spam trước đây, xác suất mail mới chứa từ này là Spam lên tới 98%. AI tự động chuyển mail vào thư mục Rác.\n\n### Ví dụ 2: Đoán môn học yêu thích qua từ khóa\n*Tình huống: Hệ thống LMS gợi ý câu lạc bộ cho học sinh lớp 10.*\n- **Đầu vào:** Học sinh hay tra cứu các từ "Robot", "Mạch điện", "Pin".\n- **Cách giải quyết:** Naive Bayes phân loại văn bản (Text Classification). Dù các từ này độc lập với nhau (giả định Naive), xác suất học sinh này thích CLB "STEM/Vật lý" cao hơn hẳn CLB "Văn học". Hệ thống hiện popup mời tham gia CLB Robotics.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Overfitting_Avoidance.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Học vẹt trong AI (Overfitting)\n*Tình huống: Huấn luyện AI dự đoán học sinh thi đỗ Đại học.*\n- **Đầu vào:** Mô hình AI đạt 100% chính xác trên tập dữ liệu lịch sử trường A.\n- **Cách giải quyết:** Khi áp dụng thực tế, AI đoán sai bét vì nó đã "học vẹt" (Overfit) các chi tiết nhiễu: nó nghĩ rằng "Cứ tên là Tuấn thì sẽ đỗ" (do vô tình dữ liệu cũ có 10 em Tuấn đều đỗ). Phải dùng Cross-validation hoặc cắt tỉa (Pruning) để AI chỉ học mẫu số chung (Pattern), bỏ qua chi tiết nhiễu.\n\n### Ví dụ 2: Overfitting trong ra đề kiểm tra\n*Tình huống: Một giáo viên dạy lý thuyết và cho sinh viên ôn tập đúng 10 câu hỏi trắc nghiệm.*\n- **Đầu vào:** Thi cuối kỳ sinh viên đạt 10 điểm toàn bộ.\n- **Cách giải quyết:** Sinh viên chỉ "Overfit" (học thuộc lòng) đáp án của 10 câu đó chứ không hiểu bản chất (Generalization). Nếu đổi đề thi sang 10 câu khác (Test set), điểm sẽ tụt xuống 2. Giải pháp: Tập ôn thi (Training set) phải rộng và đa dạng, bài thi thực tế (Test set) không được trùng lặp.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Prioritization_Matrix.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Ma trận Eisenhower cho Giáo viên chủ nhiệm\n*Tình huống: Một giáo viên có 10 việc phải làm trong ngày.*\n- **Đầu vào:** Danh sách công việc: Sửa giáo án, Họp tổ chuyên môn, Báo cáo bạo lực học đường, Chấm bài thi.\n- **Cách giải quyết:** Đặt vào ma trận: (1) Khẩn & Quan trọng (Xử lý bạo lực) -> Làm ngay. (2) Quan trọng nhưng Không khẩn (Sửa giáo án tuần sau) -> Lập lịch làm. (3) Khẩn nhưng Không quan trọng (Nộp file điểm danh cho Admin) -> Nhờ lớp trưởng làm (Delegate). (4) Loại bỏ việc lướt web.\n\n### Ví dụ 2: Ma trận RICE chọn tính năng E-learning\n*Tình huống: Phòng IT có 5 ý tưởng nâng cấp app của trường nhưng chỉ đủ ngân sách làm 1.*\n- **Đầu vào:** Chấm điểm Reach, Impact, Confidence, Effort.\n- **Cách giải quyết:** Tính năng "Push thông báo nghỉ học" có Tầm vươn (Reach) tới 100% học sinh, Tác động (Impact) lớn, Công sức (Effort) code chỉ mất 2 ngày -> RICE score cao nhất. Chọn làm trước. Tính năng "Thực tế ảo 3D" Impact cao nhưng Effort tốn 6 tháng -> RICE score thấp, đẩy xuống làm sau.\n\n'
    )
}

for path, replacement in files.items():
    if os.path.exists(path):
        with open(path, 'r', encoding='utf8') as f:
            content = f.read()
        
        if 'Rule 17: Double Examples' not in content:
            parts = content.rsplit('---\n', 1)
            if len(parts) == 2:
                new_content = parts[0] + replacement + '---\n' + parts[1]
                with open(path, 'w', encoding='utf8') as f:
                    f.write(new_content)
                print(f'Patched {path}')
            else:
                print(f'Could not split {path}')
        else:
            print(f'Already patched {path}')
