import os
import re

files = {
    '3-resources/wiki/concepts/CONCEPT_THINK_Problem_Solving_Process.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Quy trình giải quyết tình trạng gian lận thi online\n*Tình huống: Tỷ lệ sinh viên bị phát hiện copy bài thi tăng cao trong kỳ thi online.*\n- **Đầu vào:** Áp dụng 6 bước Problem Solving.\n- **Cách giải quyết:** (1) Xác định: Tool giám sát không đủ tốt. (2) Phân tích: Sinh viên dùng 1 máy khác để tra Google. (3) Đưa ra giải pháp: Bắt buộc dùng camera phụ góc rộng, hoặc đổi sang thi vấn đáp, hoặc ra đề mở. (4) Đánh giá: Đề mở là dễ triển khai nhất. (5) Áp dụng: Train giảng viên ra đề thi mở. (6) Theo dõi: Học kỳ sau không còn gian lận vì chép mạng không có đáp án.\n\n### Ví dụ 2: Quy trình tối ưu thời khóa biểu\n*Tình huống: Sinh viên thường xuyên than phiền lịch học quá trống hoặc quá kẹt.*\n- **Đầu vào:** Áp dụng Problem Solving Process.\n- **Cách giải quyết:** Áp dụng bước (1) Xác định vấn đề: Phòng đào tạo xếp lịch thủ công gây trùng lặp. Ở bước (3) và (4), họ đề xuất mua phần mềm xếp thời khóa biểu AI giá 500 triệu và thuê 1 nhân sự chuyên trách giá 100 triệu. Dựa trên ngân sách (Constraint), họ chọn phương án 2 (thuê nhân sự).\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Pros_Cons_List.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Quyết định chọn nền tảng dạy học trực tuyến\n*Tình huống: Nhà trường phân vân giữa việc dùng Microsoft Teams hay Zoom.*\n- **Đầu vào:** Lập bảng Pros & Cons.\n- **Cách giải quyết:** MS Teams - Pros: Miễn phí theo gói Office 365 sẵn có, bảo mật cao. Cons: Nặng, học sinh dùng điện thoại hay bị văng. Zoom - Pros: Rất mượt, dễ dùng, có breakout room. Cons: Tốn phí $15/tháng/Host, bảo mật kém hơn. Quyết định: Chọn MS Teams vì tiết kiệm được ngân sách lớn.\n\n### Ví dụ 2: Lựa chọn sách giáo khoa song ngữ\n*Tình huống: Chọn mua sách giáo khoa Khoa học bằng Tiếng Anh.*\n- **Đầu vào:** Đánh giá ưu nhược điểm.\n- **Cách giải quyết:** Mua bản quyền sách Anh (Pros: Chuẩn bản xứ, hình đẹp; Cons: Giá cực đắt, không sát chương trình Bộ GDĐT). Tự biên soạn (Pros: Sát thực tế, rẻ; Cons: Mất 2 năm thực hiện, giáo viên quá tải). Sau khi cân nhắc, trường chọn phương án "lai": Mua sách bản xứ làm tài liệu tham khảo thư viện, tự biên soạn handout cho lớp học.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_ROC_AUC_Evaluation.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Đánh giá mô hình lọc hồ sơ sinh viên tiềm năng\n*Tình huống: Trường dùng AI để phân loại hồ sơ ứng tuyển thành "Tiềm năng" và "Loại".*\n- **Đầu vào:** Kết quả ROC Curve của mô hình.\n- **Cách giải quyết:** Nếu đường ROC bám sát đường chéo (AUC = 0.5), AI đang đoán mò không khác gì tung đồng xu. Nếu đường ROC cong vút lên góc trái trên (AUC = 0.9), AI phân loại xuất sắc. Trường sẽ tin tưởng dùng AI này để tự động cấp thư nhập học.\n\n### Ví dụ 2: Lựa chọn Threshold (Ngưỡng) cảnh báo học vụ\n*Tình huống: AI dự báo sinh viên trượt môn. Nên đặt ngưỡng (Threshold) nhắc nhở ở mức xác suất 30% hay 70%?*\n- **Đầu vào:** Phân tích Trade-off trên đường cong ROC.\n- **Cách giải quyết:** Nếu đặt ngưỡng 30% (False Positive cao), Cố vấn học tập sẽ gọi điện nhầm cho rất nhiều sinh viên giỏi (phiền toái) nhưng bù lại không bỏ sót ai. Nếu đặt ngưỡng 70% (False Negative cao), chỉ ai rất tệ mới bị gọi, tiết kiệm sức người nhưng bỏ sót sinh viên có nguy cơ ẩn. ROC giúp BGH chọn điểm tối ưu cân bằng giữa hai rủi ro.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Root_Cause_Analysis.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Biểu đồ xương cá (Fishbone) phân tích chất lượng mạng\n*Tình huống: Điểm đánh giá học phần Tin học của học sinh giảm nghiêm trọng.*\n- **Đầu vào:** Áp dụng Biểu đồ Ishikawa (Fishbone).\n- **Cách giải quyết:** Thay vì đổ lỗi cho "Học sinh lười", phân tích 4M: Man (Giáo viên dạy chán, học sinh mất gốc), Machine (Máy tính phòng thực hành cũ, hỏng chuột), Material (Giáo trình dùng Word 2003 lỗi thời), Method (Thi trắc nghiệm thay vì thực hành). Phát hiện Root cause nằm ở Material và Machine.\n\n### Ví dụ 2: Lỗi hệ thống khi đăng ký tín chỉ\n*Tình huống: Mạng sập mỗi khi đến giờ đăng ký môn học (Course Registration).*\n- **Đầu vào:** Phân tích nguyên nhân gốc.\n- **Cách giải quyết:** IT tìm nguyên nhân: Không phải do code lởm (Symptom), mà do Server chỉ chịu được 2000 CCU. Nguyên nhân gốc rễ (Root cause): Trường không xé lẻ lịch đăng ký theo khóa (Năm 1, Năm 2) mà cho phép toàn bộ 10.000 sinh viên vào đăng ký cùng 1 lúc. Giải pháp: Phân luồng giờ đăng ký.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Similarity_Distance_Metrics.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Phát hiện đạo văn (Plagiarism Detection)\n*Tình huống: Phần mềm Turnitin kiểm tra bài luận của sinh viên.*\n- **Đầu vào:** Văn bản bài luận của sinh viên A và Wikipedia.\n- **Cách giải quyết:** Hệ thống dùng Cosine Similarity để đo góc giữa các vector từ vựng. Dù sinh viên A có cố tình thêm thắt vài từ nối, phương pháp Cosine (chỉ quan tâm hướng, không quan tâm độ dài văn bản) vẫn sẽ trả về độ tương đồng 0.95 (95% đạo văn), và đánh dấu đỏ.\n\n### Ví dụ 2: Hệ thống gợi ý khóa học (Course Recommender)\n*Tình huống: Sinh viên B vừa hoàn thành môn "Python cơ bản".*\n- **Đầu vào:** Lịch sử học tập của hàng ngàn sinh viên khác.\n- **Cách giải quyết:** Thuật toán dùng Khoảng cách Euclidean để tìm ra sinh viên C có điểm số và thời gian học gần giống hệt sinh viên B. Vì sinh viên C sau đó học môn "Phân tích dữ liệu bằng Pandas", hệ thống sẽ gợi ý môn đó cho sinh viên B.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_SVM_Linear_Separation.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: SVM phân loại bài tập tự luận\n*Tình huống: AI phân loại các đoạn văn tự luận vào 2 nhóm: "Lạc đề" và "Đúng chủ đề".*\n- **Đầu vào:** Đặc trưng của đoạn văn (số từ khóa chuyên ngành, độ dài câu).\n- **Cách giải quyết:** SVM vẽ một siêu phẳng (Hyperplane) tối ưu cắt giữa tập dữ liệu 2 nhóm trong không gian nhiều chiều. Siêu phẳng này được định hình bởi các bài luận "ranh giới" khó nhất (Support Vectors), giúp nó phân loại chính xác các bài luận mới.\n\n### Ví dụ 2: Tuyển sinh vào đội tuyển Olympic Toán\n*Tình huống: Tách học sinh khối 10 thành 2 nhóm: "Học sinh đại trà" và "Tiềm năng đội tuyển".*\n- **Đầu vào:** Điểm Toán đại số và Điểm Hình học.\n- **Cách giải quyết:** Nếu học sinh giỏi rải rác, không thể dùng 1 đường thẳng cắt ngang biểu đồ (Linear). SVM dùng kỹ thuật Kernel Trick chiếu dữ liệu lên không gian 3D, từ đó dễ dàng dùng một mặt phẳng cắt ngang để khoanh vùng chính xác nhóm học sinh tài năng xuất chúng.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_TF_IDF_Text_Mining.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Trích xuất từ khóa bài giảng điện tử\n*Tình huống: Hệ thống LMS muốn tự động tạo tag (từ khóa) cho 500 bài giảng video.*\n- **Đầu vào:** File transcript (phụ đề) của video.\n- **Cách giải quyết:** TF-IDF sẽ chấm điểm thấp cho các từ xuất hiện liên tục như "là", "và", "của" (Stop words). Nhưng nếu từ "Nhiệt động lực học" xuất hiện nhiều lần trong 1 video, nhưng hiếm khi xuất hiện ở 499 video khác, TF-IDF sẽ chấm điểm rất cao và chọn nó làm Tag chính.\n\n### Ví dụ 2: Tìm kiếm tài liệu thư viện thông minh\n*Tình huống: Sinh viên gõ "Cách tính tích phân" vào ô tìm kiếm của thư viện trường.*\n- **Đầu vào:** Hàng triệu trang tài liệu.\n- **Cách giải quyết:** Từ "Cách tính" là từ cực kỳ phổ biến (IDF thấp), nên bị hạ trọng số. Từ "Tích phân" hiếm hơn (IDF cao), nên được đẩy trọng số lên. Máy tìm kiếm sẽ ưu tiên trả về các tài liệu chứa nhiều từ "tích phân", thay vì các tài liệu hướng dẫn "cách tính" điểm trung bình.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Vision_Mockups.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Mockup ứng dụng điểm danh bằng khuôn mặt\n*Tình huống: Trường muốn gọi vốn đầu tư để làm hệ thống điểm danh AI.*\n- **Đầu vào:** Vẽ Mockup giao diện App.\n- **Cách giải quyết:** Thay vì nói suông 10 trang tài liệu kỹ thuật, Data Analyst vẽ một khung hình Figma mô phỏng cảnh cô giáo mở app, camera quét khuôn mặt 40 học sinh trong 3 giây và tick xanh toàn bộ màn hình. BGH nhìn thấy Vision (tầm nhìn) rõ ràng và lập tức duyệt ngân sách.\n\n### Ví dụ 2: Prototype báo cáo điểm trung tâm ngoại ngữ\n*Tình huống: IT team định tốn 3 tháng để xây dựng hệ thống báo cáo Tableau phức tạp.*\n- **Đầu vào:** Dùng Mockup để test nhu cầu trước.\n- **Cách giải quyết:** IT vẽ một bảng Dashboard giả trên Excel (Mockup) đưa cho Giám đốc xem thử. Giám đốc bảo: "Tôi không cần biểu đồ tròn rắc rối này, tôi chỉ cần 1 con số: Tổng học phí thu được tuần này". Nhờ Mockup, IT bỏ đi tính năng thừa, tiết kiệm 2 tháng code.\n\n'
    ),
    '3-resources/wiki/concepts/CONCEPT_THINK_Yes_No_Tree.md': (
        '## 5. Ví dụ minh họa (Rule 17: Double Examples)\n\n### Ví dụ 1: Hệ thống hỗ trợ IT tự động (Helpdesk) cho sinh viên\n*Tình huống: Sinh viên liên tục gọi điện báo "Không vào được Wi-Fi trường".*\n- **Đầu vào:** Áp dụng Yes/No Tree vào Chatbot.\n- **Cách giải quyết:** Cây logic: Cậu đang ở trong trường đúng không? (No -> Phải dùng VPN). Nếu Yes -> Cậu đã đổi mật khẩu kỳ mới chưa? (No -> Vào link X để đổi). Nếu Yes -> Đang dùng điện thoại Android phải không? (Yes -> Xem hướng dẫn cài chứng chỉ mạng). Chatbot tự động giảm 80% cuộc gọi lên IT.\n\n### Ví dụ 2: Tư vấn chọn ngành học tự động\n*Tình huống: Ngày hội tuyển sinh đại học.*\n- **Đầu vào:** Dùng Yes/No Tree để định hướng nghề nghiệp.\n- **Cách giải quyết:** Bạn có thích làm việc với con số không? (Yes). Bạn có thích giao tiếp với người khác không? (No). Bạn có thích ngồi máy tính 8 tiếng/ngày không? (Yes). Kết luận: Phù hợp ngành Khoa học dữ liệu (Data Science). Ngược lại nếu Yes-Yes, phù hợp làm Kinh doanh (Business/Sales).\n\n'
    )
}

for path, replacement in files.items():
    if os.path.exists(path):
        with open(path, 'r', encoding='utf8') as f:
            content = f.read()
        
        if 'Rule 17: Double Examples' not in content:
            parts = content.rsplit('---\n', 1)
            if len(parts) == 2:
                new_content = parts[0] + replacement + '---\n' + parts[1]
                with open(path, 'w', encoding='utf8') as f:
                    f.write(new_content)
                print(f'Patched {path}')
            else:
                print(f'Could not split {path}')
        else:
            print(f'Already patched {path}')
